# Generated by Django 6.0.2 on 2026-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mode',
            field=models.CharField(choices=[('lite', 'Лайт (Ескерту ғана)'), ('hard', 'Қатаң (Тесттен шықса бітеді)')], default='lite', max_length=10, verbose_name='Режим'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions_to_show',
            field=models.IntegerField(default=10, verbose_name='Көрсетілетін сұрақ саны'),
        ),
    ]
