# Generated by Django 6.0.2 on 2026-02-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_test_mode_test_questions_to_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='student_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
