# Generated by Django 6.0.2 on 2026-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_studentresult_student_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_students',
            field=models.IntegerField(default=100, verbose_name='Максималды оқушы саны'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions_to_show',
            field=models.IntegerField(default=20, verbose_name='Сұрақ саны (Студентке)'),
        ),
    ]
